"""Skeptic recheck of apply:object (docs/audits/deficit_object.md sections 4.1-4.3).

Two questions the apply run's own arms cannot answer:

1. REPLICATE. Do `t3_off_held` / `t3_on_held` restore T3 in an independent batch at fresh seeds (10-13), or is the
   3x figure an artefact of the one submission `apobj-les-e38d76`?
2. CONTROL FOR THE AMPUTATION ITSELF. `t3_off_held` silences 22.4 % of T3's raw input and the figure rises 2.6x.
   The audit reads that as the removal of an opposing (cancelling) carrier. The alternative reading is that removing
   ANY fifth of T3's input raises the best-cell figure (less input -> less independent noise in the denominator-free
   sum, the normalisation denominators being frozen in the neuron table). This script adds the missing arm:

       t3_nc_held: Pm5|Pm1|Mi2|Li26|Pm3|Li25 -> T3 x 0   (21.9 % of T3's raw input, EVERY pre type at the trace's
                   null: Pm5 z +0.6, Pm1 +1.5, Mi2 -0.0, Li26 -0.3, Pm3 -0.1, Li25 -0.4)

   Same post class, same amputation size, no carrier in it. If T3's figure rises there too, the 'wiring fact' of
   section 4.3 is a size-of-lesion effect; if it does not, the cancellation reading survives its control.

Nothing here edits the model or another task's files: the lesion manifest of scripts/interp_apply_object.py is
extended in-process and every other code path (record, trace, analyse) is that script's, unchanged.

    python scripts/skeptic_object_recheck.py skplan --out out/skeptic_object --seeds 10,11,12,13 --name skobj
    sh out/skeptic_object/batch.sh
    python scripts/skeptic_object_recheck.py analyse --dir out/skeptic_object --json out/interp/apply_object/skeptic_lesions.json
"""
from __future__ import annotations

import shlex
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import interp_apply_object as ao                                     # noqa: E402

EXTRA_LESIONS = {
    "t3_nc_held": {
        "kind": "edges", "pre": "Pm5|Pm1|Mi2|Li26|Pm3|Li25", "post": "T3", "factor": 0.0,
        "note": "CONTROL for the amputation size of t3_off_held: 21.9 % of T3's raw input silenced, every pre type at "
                "the object trace's null (no carrier). Asks whether removing a fifth of T3's input raises the figure "
                "by itself.",
    },
}
ao.LESIONS.update(EXTRA_LESIONS)

SK_ARMS = ("stim", "ctrl", "null")


def job_line(lid: str, arm: str, seed: int, out_dir: str, series_every: int = 5) -> str:
    """One cluster job: this script's `record` (interp_apply_object.record with the extended manifest)."""
    stem = f"{out_dir}/{lid}_{arm}_r{seed}"
    return (f"mkdir -p {out_dir} && python -c 'import torch; assert torch.cuda.is_available()' && "
            f"python scripts/skeptic_object_recheck.py record --lesion {lid} --arm {arm} --seed {seed} "
            f"--series-every {series_every} --out {stem} > {stem}.txt 2>&1; tail -3 {stem}.txt")


def cmd_skplan(args) -> int:
    """Resolve the arms on the connectome and write ONE cluster batch at the given (fresh) seeds."""
    import json
    import numpy as np
    out_dir = Path(args.out); out_dir.mkdir(parents=True, exist_ok=True)
    rel = args.out.replace("\\", "/").rstrip("/")
    seeds = [int(x) for x in args.seeds.split(",") if x]
    lids = [x for x in args.lesions.split(",") if x]
    det = [x for x in args.det_lesions.split(",") if x]
    c = ao.load_c(args.cache_dir)
    resolved = []
    for lid in lids + det:
        les = ao.lesion_record(lid)
        if les["kind"] == "edges":
            sel, pre, post = ao.edge_selection(c, les["pre"], les["post"])
            W = c.W.tocsr()
            les.update({"n_entries": int(sel.sum()), "synapses": float(np.abs(W.data[sel]).sum()),
                        "n_pre_cells": int(len(pre)), "n_post_cells": int(len(post)),
                        "share_of_post_raw_input": float(np.abs(W.data[sel]).sum() / max(np.abs(W[post].data).sum(), 1))})
        resolved.append(les)
        if les["kind"] == "edges":
            print(f"  {les['id']:12s} {les['pre']} -> {les['post']} x {les['factor']}: {les['n_entries']} entries, "
                  f"{les['synapses']:.0f} synapses, {100 * les['share_of_post_raw_input']:.1f} % of the post cells' raw input")
        else:
            print(f"  {les['id']:12s} {les['kind']}: {les.get('spec', '')}")
    jobs = [job_line(lid, arm, s, rel, args.series_every) for lid in lids for arm in SK_ARMS for s in seeds]
    jobs += [job_line(lid, arm, seeds[0], rel, args.series_every) for lid in det for arm in SK_ARMS]
    header = (f"# generated by scripts/skeptic_object_recheck.py skplan on {time.strftime('%Y-%m-%d %H:%M')}: {len(jobs)} jobs "
              f"= {len(lids)} arms x {len(SK_ARMS)} x {len(seeds)} seeds {seeds} + {len(det)} deterministic arm(s) x {len(SK_ARMS)}\n")
    ao.write_batch(out_dir / "batch.sh", args.name, args.minutes, jobs, rel, header)
    man = {"lesions": resolved, "arms": list(SK_ARMS), "seeds": seeds, "jobs": jobs, "out_dir": rel,
           "cluster_log": f"out/{args.name}_cluster.log", "connectome": ao.common.connectome_fingerprint(c),
           "date": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
    with open(out_dir / "manifest.resolved.json", "w", encoding="utf-8", newline="\n") as f:
        json.dump(ao.to_jsonable(man), f, indent=1)
    print(f"{len(jobs)} jobs -> {out_dir / 'batch.sh'} (fetch {rel}/, log out/{args.name}_cluster.log)")
    return 0


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if argv and argv[0] == "skplan":
        import argparse
        ap = argparse.ArgumentParser(prog="skeptic_object_recheck.py skplan")
        ap.add_argument("--out", default="out/skeptic_object")
        ap.add_argument("--seeds", default="10,11,12,13")
        ap.add_argument("--lesions", default="base,t3_off_held,t3_on_held,t3_nc_held")
        ap.add_argument("--det-lesions", default="fb0", help="arms that are deterministic: one seed only")
        ap.add_argument("--name", default="skobj"); ap.add_argument("--minutes", type=int, default=45)
        ap.add_argument("--series-every", type=int, default=5); ap.add_argument("--cache-dir", default=None)
        return cmd_skplan(ap.parse_args(argv[1:]))
    return ao.main(argv)


if __name__ == "__main__":
    import os
    os.environ.setdefault("PYTHONIOENCODING", "utf-8")
    sys.exit(main())
